# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='news.proto',
  package='news.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nnews.proto\x12\rnews.protobuf\"v\n\x04News\x12\x10\n\x08keywords\x18\x01 \x03(\t\x12\'\n\x05posts\x18\x02 \x03(\x0b\x32\x18.news.protobuf.News.Post\x1a\x33\n\x04Post\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07post_at\x18\x03 \x01(\x05\x62\x06proto3')
)




_NEWS_POST = _descriptor.Descriptor(
  name='Post',
  full_name='news.protobuf.News.Post',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='news.protobuf.News.Post.rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='news.protobuf.News.Post.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_at', full_name='news.protobuf.News.Post.post_at', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=147,
)

_NEWS = _descriptor.Descriptor(
  name='News',
  full_name='news.protobuf.News',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='news.protobuf.News.keywords', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posts', full_name='news.protobuf.News.posts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NEWS_POST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=147,
)

_NEWS_POST.containing_type = _NEWS
_NEWS.fields_by_name['posts'].message_type = _NEWS_POST
DESCRIPTOR.message_types_by_name['News'] = _NEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

News = _reflection.GeneratedProtocolMessageType('News', (_message.Message,), dict(

  Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), dict(
    DESCRIPTOR = _NEWS_POST,
    __module__ = 'news_pb2'
    # @@protoc_insertion_point(class_scope:news.protobuf.News.Post)
    ))
  ,
  DESCRIPTOR = _NEWS,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:news.protobuf.News)
  ))
_sym_db.RegisterMessage(News)
_sym_db.RegisterMessage(News.Post)


# @@protoc_insertion_point(module_scope)
