// Code generated by protoc-gen-go. DO NOT EDIT.
// source: news.proto

package news_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type News struct {
	Keywords             []string     `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Posts                []*News_Post `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *News) Reset()         { *m = News{} }
func (m *News) String() string { return proto.CompactTextString(m) }
func (*News) ProtoMessage()    {}
func (*News) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{0}
}

func (m *News) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_News.Unmarshal(m, b)
}
func (m *News) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_News.Marshal(b, m, deterministic)
}
func (m *News) XXX_Merge(src proto.Message) {
	xxx_messageInfo_News.Merge(m, src)
}
func (m *News) XXX_Size() int {
	return xxx_messageInfo_News.Size(m)
}
func (m *News) XXX_DiscardUnknown() {
	xxx_messageInfo_News.DiscardUnknown(m)
}

var xxx_messageInfo_News proto.InternalMessageInfo

func (m *News) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *News) GetPosts() []*News_Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type News_Post struct {
	Rank                 int32    `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	PostAt               int32    `protobuf:"varint,3,opt,name=post_at,json=postAt,proto3" json:"post_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *News_Post) Reset()         { *m = News_Post{} }
func (m *News_Post) String() string { return proto.CompactTextString(m) }
func (*News_Post) ProtoMessage()    {}
func (*News_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{0, 0}
}

func (m *News_Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_News_Post.Unmarshal(m, b)
}
func (m *News_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_News_Post.Marshal(b, m, deterministic)
}
func (m *News_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_News_Post.Merge(m, src)
}
func (m *News_Post) XXX_Size() int {
	return xxx_messageInfo_News_Post.Size(m)
}
func (m *News_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_News_Post.DiscardUnknown(m)
}

var xxx_messageInfo_News_Post proto.InternalMessageInfo

func (m *News_Post) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *News_Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *News_Post) GetPostAt() int32 {
	if m != nil {
		return m.PostAt
	}
	return 0
}

func init() {
	proto.RegisterType((*News)(nil), "news.protobuf.News")
	proto.RegisterType((*News_Post)(nil), "news.protobuf.News.Post")
}

func init() { proto.RegisterFile("news.proto", fileDescriptor_2c0382e93bed6d84) }

var fileDescriptor_2c0382e93bed6d84 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4b, 0x2d, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0xb0, 0x93, 0x4a, 0xd3, 0x94, 0x66, 0x33,
	0x72, 0xb1, 0xf8, 0xa5, 0x96, 0x17, 0x0b, 0x49, 0x71, 0x71, 0x64, 0xa7, 0x56, 0x96, 0xe7, 0x17,
	0xa5, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x7a, 0x5c, 0xac, 0x05,
	0xf9, 0xc5, 0x25, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x12, 0x7a, 0x28, 0x66, 0xe8,
	0x81, 0xf4, 0xeb, 0x05, 0xe4, 0x17, 0x97, 0x04, 0x41, 0x94, 0x49, 0xb9, 0x73, 0xb1, 0x80, 0xb8,
	0x42, 0x42, 0x5c, 0x2c, 0x45, 0x89, 0x79, 0xd9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60,
	0x36, 0x48, 0xac, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16,
	0x12, 0xe7, 0x62, 0x07, 0x69, 0x8c, 0x4f, 0x2c, 0x91, 0x60, 0x06, 0x2b, 0x65, 0x03, 0x71, 0x1d,
	0x4b, 0x92, 0xd8, 0xc0, 0x76, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x03, 0x23, 0xd6, 0x0f,
	0xc1, 0x00, 0x00, 0x00,
}
